--- 
- name: Playbook para healthcheck de DNS
  hosts: localhost
  gather_facts: false
  vars:
    urls:
      - "bcb.gov.br"
      - "teste.fdsfds"
    dns_servers:
      - "8.8.8.8"
      - "172.53.53.53"
    dns_timeout: 3
    max_response_time_ms: 100

  tasks:
    - name: "Executa resolução DNS para cada URL em cada DNS"
      vars:
        url_item: "{{ item.0 }}"
        dns_item: "{{ item.1 }}"
      command: "dig @{{ dns_item }} +short +stats +time={{ dns_timeout }} {{ url_item }}"
      register: dig_out
      loop: "{{ urls | product(dns_servers) | list }}"
      loop_control:
        label: "{{ url_item }} @{{ dns_item }}"
      ignore_errors: yes

    - name: Formata resultado
      set_fact:
        resultado_dns: "{{ resultado_dns | default([]) + [ {
          'URL': item.item.0,
          'DNS_SERVER': item.item.1,
          'CONECTIVIDADE': 'OK' if (item.rc == 0 and not ('connection timed out' in item.stderr or 'no servers could be reached' in item.stderr)) else 'NOK',
          'TEMPO_DE_RESPOSTA': (
              'NORMAL (' ~ (query_time_ms | int | string) ~ ' ms)'
                if (query_time_ms | int) <= (max_response_time_ms | int)
              else 'ALTA - ' ~ (query_time_ms | int | string) ~ ' ms'
                ),
          'DOMINIO_EXISTENTE':
            'NOK' if ('status: NXDOMAIN' in item.stdout)
                else (
            'N/A' if (
              'status:' not in item.stdout or
              'status: SERVFAIL' in item.stdout or
              'status: REFUSED' in item.stdout
            )
            else 'OK'
            ),
          'RESOLVIDO_PARA': (
              (item.stdout | default(''))
              | regex_replace('^;.*$', '', multiline=True)
              | regex_findall('(?m)^(?:\\d{1,3}\\.){3}\\d{1,3}$')
              | join(', ')) }] }}" 
      vars:
        query_time_line: "{{ item.stdout | regex_search(';; Query time: (\\d+) msec', '\\1') }}"
        query_time_ms: "{{ query_time_line[0] | default('0') if query_time_line else 0 }}"
      loop: "{{ dig_out.results }}"
      loop_control:
        label: "{{ item.item.0 }} @{{ item.item.1 }}"

    - name: Avalia status geral do healthcheck de DNS
      set_fact:
        healthcheck_dns_status: >-
          {{
            resultado_dns | selectattr('CONECTIVIDADE', 'equalto', 'NOK') | list | length > 0
            or resultado_dns | selectattr('Non-existent domain', 'equalto', 'NOK') | list | length > 0
            or resultado_dns | selectattr('TEMPO_DE_RESPOSTA', 'search', 'ALTA') | list | length > 0
          }}

    - name: Exibe resultado de healthcheck de DNS
      debug:
        msg: 
          HEALTHCHECK: "{{ 'NOK' if healthcheck_dns_status else 'OK' }}"
          DIAGNÓSTICO:
            - DNS: "{{ resultado_dns}}" 
