---
- name: Playbook para healthcheck de uso de CPU e mem贸ria em Linux
  hosts: 172.29.194.140
  gather_facts: no
  tasks:
    - name: Adiciona o host da VM
      add_host:
        name: "{{ target_ip }}"
        groups: vm_target
        ansible_user: "{{ target_user }}"
        ansible_connection: ssh


  tasks:
    - name: Verificar uso de CPU para o Host "{{ inventory_hostname }}" 
      ansible.builtin.shell: |
        top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}'
      register: cpu_usage

    - name: Verificar uso de mem贸ria para o Host "{{ inventory_hostname }}" 
      ansible.builtin.shell: |
        free | grep Mem | awk '{printf("%.2f", $3/$2 * 100.0)}'
      register: memory_usage

    - name: Exibir uso de CPU e mem贸ria para o Host "{{ inventory_hostname }}"
      debug:
        msg: "Servidor: {{ inventory_hostname }} | CPU: {{ cpu_usage.stdout }}% | Mem贸ria: {{ memory_usage.stdout }}%"





