---
- name: Playbook para healthcheck de uso de CPU e mem贸ria em Linux
  hosts: all
  gather_facts: no
  tasks:
    - name: Adiciona host dinamicamente
      add_host:
        name: "{{ target_ip }}"
        ansible_host: "{{ target_ip }}"
        ansible_user: "{{ ssh_user }}"
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3
    - name: Executa tarefas no host adicionado
      delegate_to: "{{ target_ip }}"
      command: uptime

  
  tasks:
    - name: Verificar uso de CPU para o Host "{{ inventory_hostname }}" 
      ansible.builtin.shell: |
        top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}'
      register: cpu_usage

    - name: Verificar uso de mem贸ria para o Host "{{ inventory_hostname }}" 
      ansible.builtin.shell: |
        free | grep Mem | awk '{printf("%.2f", $3/$2 * 100.0)}'
      register: memory_usage

    - name: Exibir uso de CPU e mem贸ria para o Host "{{ inventory_hostname }}"
      debug:
        msg: "Servidor: {{ inventory_hostname }} | CPU: {{ cpu_usage.stdout }}% | Mem贸ria: {{ memory_usage.stdout }}%"





