---
- name: Check URLs and send status to Dynatrace
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    urls:
      - https://www.google.com.br

    dynatrace_log_api: "https://nev24035.apps.dynatrace.com.live.dynatrace.com/api/v2/logs/ingest"
    dynatrace_token: ""

  tasks:

    - name: Check each URL
      uri:
        url: "{{ item }}"
        method: GET
        return_content: no
        status_code: 200
        validate_certs: no
      register: url_status
      loop: "{{ urls }}"
      ignore_errors: true

    - name: teste
      debug:
        msg: "{{ url_status }}"
        
    - name: Send logs to Dynatrace
      uri:
        url: "{{ dynatrace_log_api }}"
        method: POST
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
          Content-Type: "application/json"
        body_format: json
        body: "{{ dynatrace_logs }}"
      delegate_to: localhost
